package reporting

import (
	"fmt"

	"github.com/jung-kurt/gofpdf"
)

func ExportIncidentReportPDF(r IncidentReport, path string) error {

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()

	// ================= HEADER =================
	pdf.SetFillColor(15, 23, 42)
	pdf.Rect(0, 0, 210, 20, "F")

	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Arial", "B", 14)
	pdf.SetXY(10, 6)
	pdf.Cell(0, 10, "SentinelX Security Report")

	pdf.Ln(15)
	pdf.SetTextColor(0, 0, 0)

	// ================= TITLE =================
	pdf.SetFont("Arial", "B", 18)
	pdf.Cell(0, 10, r.Title)
	pdf.Ln(10)

	pdf.SetFont("Arial", "", 10)
	pdf.Cell(0, 6, "Incident ID: "+r.IncidentID)
	pdf.Ln(5)
	pdf.Cell(0, 6, "Generated At: "+r.GeneratedAt)
	pdf.Ln(10)

	// ================= SUMMARY =================
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "Executive Summary")
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 11)
	pdf.MultiCell(0, 6, r.ExecutiveSummary, "", "", false)
	pdf.Ln(6)

	// ================= INCIDENT DETAILS =================
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "Incident Details")
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 11)

	pdf.Cell(0, 6, "Source IP: "+r.SourceIP)
	pdf.Ln(6)

	pdf.Cell(0, 6, "Attack Type: "+r.AttackType)
	pdf.Ln(6)

	pdf.Cell(0, 6, "Risk Level: "+r.RiskLevel)
	pdf.Ln(6)

	// Severity color
	pdf.Cell(40, 6, "Severity:")
	switch r.Severity {
	case "critical":
		pdf.SetTextColor(220, 38, 38)
	case "high":
		pdf.SetTextColor(249, 115, 22)
	case "medium":
		pdf.SetTextColor(234, 179, 8)
	default:
		pdf.SetTextColor(34, 197, 94)
	}
	pdf.Cell(0, 6, r.Severity)
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(6)

	pdf.Cell(0, 6, fmt.Sprintf("Threat Score: %.2f", r.ThreatScore))
	pdf.Ln(8)

	// ================= TIMELINE =================
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "Attack Timeline")
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 10)

	if len(r.AttackChain) == 0 {
		pdf.Cell(0, 6, "No timeline available")
		pdf.Ln(6)
	} else {
		for _, step := range r.AttackChain {
			line := fmt.Sprintf("[%s] %s -> %s",
				step.Timestamp,
				step.Stage,
				step.EventType,
			)
			pdf.Cell(0, 8, line)
			pdf.Ln(6)
		}
	}
	pdf.Ln(4)

	// ================= MITRE =================
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "MITRE ATT&CK Mapping")
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 11)

	if r.MitreTactic == "" {
		pdf.Cell(0, 6, "Tactic: Initial Access")
		pdf.Ln(6)
		pdf.Cell(0, 6, "Technique: Suspicious Network Activity")
	} else {
		pdf.Cell(0, 6, "Tactic: "+r.MitreTactic)
		pdf.Ln(6)
		pdf.Cell(0, 6, "Technique: "+r.MitreTechnique)
	}
	pdf.Ln(6)

	pdf.Ln(4)

	// ================= ACTIONS =================
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "Actions Taken")
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 10)

	if len(r.ActionsTaken) == 0 {
		defaultActions := []string{
			"Traffic blocked at firewall",
			"Source IP flagged",
			"Alert generated in system",
		}

		for _, a := range defaultActions {
			pdf.Cell(0, 6, "- "+a)
			pdf.Ln(6)
		}
	} else {
		for _, a := range r.ActionsTaken {
			pdf.Cell(0, 6, "- "+a.Action)
			pdf.Ln(6)
		}
	}

	pdf.Ln(4)

	// ================= EVIDENCE =================
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "Evidence")
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 10)

	if len(r.Evidence) == 0 {
		pdf.Cell(0, 6, "No evidence available")
		pdf.Ln(6)
	} else {
		for _, e := range r.Evidence {
			line := fmt.Sprintf("[%s] %s",
				e.Type,
				e.Summary,
			)
			pdf.MultiCell(180, 5, line, "", "", false)
			pdf.Ln(2)
		}
	}

	pdf.Ln(4)

	// ================= RECOMMENDATIONS =================
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "Recommendations")
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 11)

	for _, rec := range r.RecommendedRemediation {
		pdf.Cell(0, 6, "- "+rec)
		pdf.Ln(6)
	}

	// ================= FOOTER =================
	pdf.SetY(-15)
	pdf.SetFont("Arial", "I", 8)
	pdf.Cell(0, 10, "Generated by SentinelX - Security Platform")

	return pdf.OutputFileAndClose(path)
}

