package detection

import (
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"sentinelx/correlation"
	"sentinelx/incident"
	"sentinelx/metrics"
	"sentinelx/models"
	"sentinelx/storage"
	"sentinelx/stream"
)

// AlertQueue stores alerts generated by detection engines
var AlertQueue chan models.Alert

// Recent alerts (for dashboard)
var recentAlerts []models.Alert
var alertMu sync.RWMutex

// InitAlertEngine initializes the alert system
func InitAlertEngine(size int) {
	AlertQueue = make(chan models.Alert, size)
	fmt.Println("Alert Engine initialized")
}

// GenerateAlert creates and pushes alert to queue
func GenerateAlert(alertType, ip, description string) {
	severity := ClassifySeverity(alertType)

	alert := models.Alert{
		ID:          fmt.Sprintf("ALT-%d", time.Now().UnixNano()),
		Timestamp:   time.Now(),
		Type:        alertType,
		SourceIP:    ip,
		Severity:    severity,
		Description: description,
	}

	// Record real attack event
	correlation.RecordEvent(ip, alertType)

	// Detect multi-stage attack
	if correlation.DetectMultiStage(ip) {
		multiAlert := models.Alert{
			ID:          fmt.Sprintf("ALT-%d", time.Now().UnixNano()),
			Timestamp:   time.Now(),
			Type:        "MULTI_STAGE_ATTACK",
			SourceIP:    ip,
			Severity:    "CRITICAL",
			Description: "Possible coordinated attack detected",
		}

		incident.CreateIncident(multiAlert.ID, multiAlert.Type, multiAlert.Severity)

		select {
		case AlertQueue <- multiAlert:
		default:
			fmt.Println("Alert queue full — dropping multi-stage alert")
		}
	}

	// Deduplication check
	if shouldSuppress(alert) {
		return
	}

	incident.CreateIncident(alert.ID, alert.Type, alert.Severity)

	select {
	case AlertQueue <- alert:
	default:
		fmt.Println("Alert queue full — dropping alert")
	}
}

// StartAlertProcessor consumes alerts from queue
func StartAlertProcessor() {
	fmt.Println("Alert Processor started")

	for alert := range AlertQueue {
		fmt.Println("DEBUG: alert received in processor")

		AddRecentAlert(alert)

		data, _ := json.Marshal(alert)
		fmt.Println("DEBUG: broadcasting alert:", string(data))

		stream.BroadcastAlert(data)

		dispatchConsole(alert)
		dispatchLog(alert)
	}
}

// dispatchConsole prints alerts to terminal
func dispatchConsole(alert models.Alert) {
	metrics.RecordAlert()

	fmt.Println("========= SECURITY ALERT =========")
	fmt.Println("ID:", alert.ID)
	fmt.Println("Type:", alert.Type)
	fmt.Println("Source IP:", alert.SourceIP)
	fmt.Println("Severity:", alert.Severity)
	fmt.Println("Description:", alert.Description)
	fmt.Println("Timestamp:", alert.Timestamp)
	fmt.Println("==================================")
}

// dispatchLog stores alert in persistent log
func dispatchLog(alert models.Alert) {
	storage.LogAlert(alert)
	storage.SaveAlert(alert)
}

// AddRecentAlert stores alert for dashboard
func AddRecentAlert(alert models.Alert) {
	alertMu.Lock()
	defer alertMu.Unlock()

	recentAlerts = append(recentAlerts, alert)

	if len(recentAlerts) > 50 {
		recentAlerts = recentAlerts[1:]
	}
}

// GetRecentAlerts returns a safe copy
func GetRecentAlerts() []models.Alert {
	alertMu.RLock()
	defer alertMu.RUnlock()

	cpy := make([]models.Alert, len(recentAlerts))
	copy(cpy, recentAlerts)

	for i, j := 0, len(cpy)-1; i < j; i, j = i+1, j-1 {
		cpy[i], cpy[j] = cpy[j], cpy[i]
	}

	return cpy
}

// ClassifySeverity determines severity automatically
func ClassifySeverity(alertType string) string {
	switch alertType {
	case "PORT_SCAN":
		return "MEDIUM"
	case "SQL_INJECTION":
		return "CRITICAL"
	case "XSS_ATTACK":
		return "HIGH"
	case "DIR_TRAVERSAL":
		return "HIGH"
	case "BRUTE_FORCE":
		return "HIGH"
	case "MULTI_STAGE_ATTACK":
		return "CRITICAL"
	case "THREAT_INTEL_MATCH":
		return "CRITICAL"
	case "repeated_http_requests":
		return "HIGH"
	case "admin_access_watch":
		return "CRITICAL"
	default:
		return "LOW"
	}
}