package detection

import (
	"fmt"
	"time"

	"sentinelx/models"
	"sentinelx/storage"
	"sentinelx/metrics"
)

// AlertQueue stores alerts generated by detection engines
var AlertQueue chan models.Alert

// InitAlertEngine initializes the alert system
func InitAlertEngine(size int) {

	AlertQueue = make(chan models.Alert, size)

	fmt.Println("Alert Engine initialized")

}

// GenerateAlert creates and pushes alert to queue
func GenerateAlert(alertType, ip, description string) {

	severity := ClassifySeverity(alertType)

	alert := models.Alert{
		Timestamp:   time.Now().Unix(),
		Type:        alertType,
		SourceIP:    ip,
		Severity:    severity,
		Description: description,
	}

	if shouldSuppress(alert) {
	return
}

	select {

	case AlertQueue <- alert:

	default:
		fmt.Println("Alert queue full — dropping alert")

	}

}

// StartAlertProcessor consumes alerts from queue
func StartAlertProcessor() {

	fmt.Println("Alert Processor started")

	for alert := range AlertQueue {

		dispatchConsole(alert)

		dispatchLog(alert)

	}

}

//
// DISPATCHERS
//

// dispatchConsole prints alerts to terminal
func dispatchConsole(alert models.Alert) {

	metrics.RecordAlert()

	fmt.Println("========= SECURITY ALERT =========")

	fmt.Println("Type:", alert.Type)

	fmt.Println("Source IP:", alert.SourceIP)

	fmt.Println("Severity:", alert.Severity)

	fmt.Println("Description:", alert.Description)

	fmt.Println("Timestamp:", alert.Timestamp)

	fmt.Println("==================================")

}

// dispatchLog stores alert in persistent log
func dispatchLog(alert models.Alert) {

	storage.LogAlert(alert)

}

//
// SEVERITY CLASSIFICATION
//

// ClassifySeverity determines severity automatically
func ClassifySeverity(alertType string) string {

	switch alertType {

	case "PORT_SCAN":
		return "MEDIUM"

	case "SQL_INJECTION":
		return "CRITICAL"

	case "XSS_ATTACK":
		return "HIGH"

	case "DIR_TRAVERSAL":
		return "HIGH"

	case "BRUTE_FORCE":
		return "HIGH"

	default:
		return "LOW"

	}

}