package detection

import (
	"fmt"
	"sync"
	"time"

	"sentinelx/correlation"
	"sentinelx/metrics"
	"sentinelx/models"
	"sentinelx/response"
	"sentinelx/storage"
	"sentinelx/stream"
)

// AlertQueue stores alerts generated by detection engines
var AlertQueue chan models.Alert

// Recent alerts (for dashboard)
var recentAlerts []models.Alert
var alertMu sync.RWMutex

// InitAlertEngine initializes the alert system
func InitAlertEngine(size int) {
	AlertQueue = make(chan models.Alert, size)
	fmt.Println("Alert Engine initialized")
}

// GenerateAlert creates and pushes alert to queue
func GenerateAlert(alertType, ip, description string) {
	severity := ClassifySeverity(alertType)

	alert := models.Alert{
		ID:          fmt.Sprintf("ALT-%d", time.Now().UnixNano()),
		Timestamp:   time.Now().UTC(),
		Type:        alertType,
		SourceIP:    ip,
		Severity:    severity,
		Description: description,
		ThreatScore: models.ThreatScoreFromSeverity(severity),
		Status:      models.AlertStatusNew,
		Metadata:    map[string]interface{}{},
	}

	// Record real attack event
	correlation.RecordEvent(ip, alertType)

	// Detect multi-stage attack
	if correlation.DetectMultiStage(ip) {
		multiSeverity := ClassifySeverity("MULTI_STAGE_ATTACK")

		multiAlert := models.Alert{
			ID:          fmt.Sprintf("ALT-%d", time.Now().UnixNano()),
			Timestamp:   time.Now().UTC(),
			Type:        "MULTI_STAGE_ATTACK",
			SourceIP:    ip,
			Severity:    multiSeverity,
			Description: "Possible coordinated attack detected",
			ThreatScore: models.ThreatScoreFromSeverity(multiSeverity),
			Status:      models.AlertStatusNew,
			Metadata:    map[string]interface{}{},
		}

		select {
		case AlertQueue <- multiAlert:
		default:
			fmt.Println("Alert queue full - dropping multi-stage alert")
		}
	}

	// Deduplication check
	if shouldSuppress(alert) {
		return
	}

	select {
	case AlertQueue <- alert:
	default:
		fmt.Println("Alert queue full - dropping alert")
	}
}

// StartAlertProcessor consumes alerts from queue
func StartAlertProcessor() {
	fmt.Println("Alert Processor started")

	for alert := range AlertQueue {
		fmt.Println("DEBUG: alert received in processor")
		alert = applyThreatScoring(alert)

		AddRecentAlert(alert)

		fmt.Println("DEBUG: broadcasting alert:", alert.ID)
		stream.BroadcastAlert(alert)

		dispatchConsole(alert)
		dispatchLog(alert)
		response.ProcessAlert(alert)
	}
}

func applyThreatScoring(alert models.Alert) models.Alert {
	scorer := NewThreatScorer()

	signals := DefaultSignalsFromEvent(
		alert.ID,
		alert.Type,
		alert.SourceIP,
		alert.Target,
		alert.Description,
		alert.Severity,
	)
	signals.Metadata = alert.Metadata

	result := scorer.ScoreWithContext(signals)

	alert.Severity = result.Severity
	alert.ThreatScore = result.ThreatScore

	meta := result.ToAlertMetadata()
	for k, v := range alert.Metadata {
		meta[k] = v
	}
	alert.Metadata = meta

	return alert
}

// dispatchConsole prints alerts to terminal
func dispatchConsole(alert models.Alert) {
	metrics.RecordAlert()

	fmt.Println("========= SECURITY ALERT =========")
	fmt.Println("ID:", alert.ID)
	fmt.Println("Type:", alert.Type)
	fmt.Println("Source IP:", alert.SourceIP)
	fmt.Println("Severity:", alert.Severity)
	fmt.Println("Threat Score:", alert.ThreatScore)
	fmt.Println("Status:", alert.Status)
	fmt.Println("Description:", alert.Description)
	fmt.Println("Timestamp:", alert.Timestamp)
	fmt.Println("==================================")
}

// dispatchLog stores alert in persistent log
func dispatchLog(alert models.Alert) {
	storage.LogAlert(alert)
	storage.SaveAlert(alert)
}

// AddRecentAlert stores alert for dashboard
func AddRecentAlert(alert models.Alert) {
	alertMu.Lock()
	defer alertMu.Unlock()

	recentAlerts = append(recentAlerts, alert)

	if len(recentAlerts) > 50 {
		recentAlerts = recentAlerts[1:]
	}
}

// GetRecentAlerts returns a safe copy
func GetRecentAlerts() []models.Alert {
	alertMu.RLock()
	defer alertMu.RUnlock()

	cpy := make([]models.Alert, len(recentAlerts))
	copy(cpy, recentAlerts)

	for i, j := 0, len(cpy)-1; i < j; i, j = i+1, j-1 {
		cpy[i], cpy[j] = cpy[j], cpy[i]
	}

	return cpy
}

// ClassifySeverity determines severity automatically
func ClassifySeverity(alertType string) string {
	switch alertType {
	case "PORT_SCAN":
		return models.SeverityMedium
	case "SQL_INJECTION":
		return models.SeverityCritical
	case "XSS_ATTACK":
		return models.SeverityHigh
	case "DIR_TRAVERSAL":
		return models.SeverityHigh
	case "BRUTE_FORCE":
		return models.SeverityHigh
	case "MULTI_STAGE_ATTACK":
		return models.SeverityCritical
	case "THREAT_INTEL_MATCH":
		return models.SeverityCritical
	case "repeated_http_requests":
		return models.SeverityHigh
	case "admin_access_watch":
		return models.SeverityCritical
	default:
		return models.SeverityLow
	}
}
